// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Rabbit

#ifndef _RABBIT_UI_H
#define _RABBIT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_events.h"
void bounce_Animation( lv_obj_t *TargetObject, int delay);
void earsDown_Animation( lv_obj_t *TargetObject, int delay);
void earsUp_Animation( lv_obj_t *TargetObject, int delay);
void ears_Animation( lv_obj_t *TargetObject, int delay);
void ui_event_homeScreen( lv_event_t * e);
extern lv_obj_t *ui_homeScreen;
extern lv_obj_t *ui_rabbit;
extern lv_obj_t *ui_earRight;
extern lv_obj_t *ui_body;
extern lv_obj_t *ui_earLeft;
extern lv_obj_t *ui_timeLabel;
extern lv_obj_t *ui_batteryLabel;
extern lv_obj_t *ui_alertlabel;
void ui_event_musicPanel( lv_event_t * e);
extern lv_obj_t *ui_musicPanel;
void ui_event_musicPrevious( lv_event_t * e);
extern lv_obj_t *ui_musicPrevious;
void ui_event_musicPlay( lv_event_t * e);
extern lv_obj_t *ui_musicPlay;
void ui_event_musicNext( lv_event_t * e);
extern lv_obj_t *ui_musicNext;
void ui_event_weatherScreen( lv_event_t * e);
extern lv_obj_t *ui_weatherScreen;
extern lv_obj_t *ui_tempLabel;
extern lv_obj_t *ui_cityLabel;
extern lv_obj_t *ui_weatherIcon;
extern lv_obj_t *ui_rainLabel;
extern lv_obj_t *ui_humidityLabel;
extern lv_obj_t *ui_windLabel;
extern lv_obj_t *ui_forecastPanel;
extern lv_obj_t *ui_forecastItem;
extern lv_obj_t *ui_forecastDay;
extern lv_obj_t *ui_forecastIcon;
extern lv_obj_t *ui_forecastLabel;
extern lv_obj_t *ui_forecastTitle;
extern lv_obj_t *ui_tempHighLabel;
extern lv_obj_t *ui_tempLowLabel;
void ui_event_notificationScreen( lv_event_t * e);
extern lv_obj_t *ui_notificationScreen;
extern lv_obj_t *ui_notificationPanel;
extern lv_obj_t *ui_notificationItem;
extern lv_obj_t *ui_notificationTitle;
extern lv_obj_t *ui_notificationTime;
extern lv_obj_t *ui_notificationText;
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;


LV_IMG_DECLARE( ui_img_r_ear_54_png);   // assets\r_ear_54.png
LV_IMG_DECLARE( ui_img_r_body_90_png);   // assets\r_body_90.png
LV_IMG_DECLARE( ui_img_back_32_png);   // assets\back_32.png
LV_IMG_DECLARE( ui_img_32_play_png);   // assets\32_play.png
LV_IMG_DECLARE( ui_img_next_32_png);   // assets\next_32.png
LV_IMG_DECLARE( ui_img_dy0_png);   // assets\dy0.png
LV_IMG_DECLARE( ui_img_dy3_png);   // assets\dy3.png
LV_IMG_DECLARE( ui_img_2052995423);   // assets\1-208324.png
LV_IMG_DECLARE( ui_img_484901176);   // assets\7-162814.png
LV_IMG_DECLARE( ui_img_back_l32_png);   // assets\back_l32.png
LV_IMG_DECLARE( ui_img_close_l32_png);   // assets\close_l32.png
LV_IMG_DECLARE( ui_img_dy1_png);   // assets\dy1.png
LV_IMG_DECLARE( ui_img_dy2_png);   // assets\dy2.png
LV_IMG_DECLARE( ui_img_dy4_png);   // assets\dy4.png
LV_IMG_DECLARE( ui_img_dy5_png);   // assets\dy5.png
LV_IMG_DECLARE( ui_img_dy6_png);   // assets\dy6.png
LV_IMG_DECLARE( ui_img_dy7_png);   // assets\dy7.png
LV_IMG_DECLARE( ui_img_electron_32_png);   // assets\electron_32.png
LV_IMG_DECLARE( ui_img_heart2_png);   // assets\heart2.png
LV_IMG_DECLARE( ui_img_hw21_png);   // assets\hw21.png
LV_IMG_DECLARE( ui_img_kb_1_png);   // assets\kb_1.png
LV_IMG_DECLARE( ui_img_kb_2_png);   // assets\kb_2.png
LV_IMG_DECLARE( ui_img_kg_1_png);   // assets\kg_1.png
LV_IMG_DECLARE( ui_img_kg_2_png);   // assets\kg_2.png
LV_IMG_DECLARE( ui_img_k_1_png);   // assets\k_1.png
LV_IMG_DECLARE( ui_img_k_2_png);   // assets\k_2.png
LV_IMG_DECLARE( ui_img_next_l32_png);   // assets\next_l32.png
LV_IMG_DECLARE( ui_img_nt0_png);   // assets\nt0.png
LV_IMG_DECLARE( ui_img_nt1_png);   // assets\nt1.png
LV_IMG_DECLARE( ui_img_nt2_png);   // assets\nt2.png
LV_IMG_DECLARE( ui_img_nt3_png);   // assets\nt3.png
LV_IMG_DECLARE( ui_img_nt4_png);   // assets\nt4.png
LV_IMG_DECLARE( ui_img_nt5_png);   // assets\nt5.png
LV_IMG_DECLARE( ui_img_nt6_png);   // assets\nt6.png
LV_IMG_DECLARE( ui_img_nt7_png);   // assets\nt7.png
LV_IMG_DECLARE( ui_img_search_32_png);   // assets\search_32.png


LV_FONT_DECLARE( ui_font_bolld_100);
LV_FONT_DECLARE( ui_font_Font1);
LV_FONT_DECLARE( ui_font_regular100);
LV_FONT_DECLARE( ui_font_regular_120);
LV_FONT_DECLARE( ui_font_semi100);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
