// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: Rabbit

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onMusicPrevious(lv_event_t * e);
void onMusicPlay(lv_event_t * e);
void onMusicNext(lv_event_t * e);
void onWeatherOpen(lv_event_t * e);
void onNotificationOpen(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
